### ISSUE TITLE
TODO!

### ISSUE THREAD

**Issue by Dannyholt** [beaverbuilder/documentation#143]
- [x] Move docs into separate doc instances
- [x] Correct all internal links
- [x] Update netlify.toml
  - [x] Remove `/` from end of URLs in netlify.toml
- [x] Update field connection list [here](https://docs.wpbeaverbuilder.com/beaver-themer/field-connections/field-connection-shortcode-index-themer/)
- [x] Update info for fixing `destination folder already exists` [here](https://docs.wpbeaverbuilder.com/beaver-builder/troubleshooting/common-issues/destination-folder-already-exists/)
- [x] Add YouTube to footer links
- [x] Add get it now button to header replacing Alpha/Beta docs link

### General is now FAQ

- [x] /faq/overview // Index
- [x] /faq/frequently-asked-questions
- [x] /faq/manage-account/overview // Index
  - [x] /faq/manage-account/my-account-page-overview
  - [x] /faq/manage-account/view-your-license
  - [x] /faq/manage-account/change-email-address-or-password-for-your-beaver-builder-account
  - [x] /faq/manage-account/manage-your-credit-card-information
  - [x] /faq/manage-account/manage-plugin-activations-centrally
  - [x] /faq/manage-account/restore-a-removed-domain-in-domain-manager
  - [x] /faq/manage-account/my-beaver-builder-license-was-deactivated
  - [x] /faq/manage-account/renew-your-beaver-builder-subscription
  - [x] /faq/manage-account/upgrade-your-premium-license
  - [x] /faq/manage-account/cancel-your-automatic-renewal
  - [x] /faq/manage-account/downgrade-to-a-lower-version-of-beaver-builder
  - [x] /faq/manage-account/license-suspension
  - [x] /faq/manage-account/request-an-invoice
  - [x] /faq/manage-account/suggest-new-features
- [x] /faq/support-policy
- [x] /faq/accessibility
- [x] /faq/gdpr
- [x] /faq/glossary
- [x] /faq/translations
- [x] /faq/software-releases-and-versioning
- [x] /faq/alpha-and-beta-releases
